name: test-assessment

x-node-app: &node-app-dev
  image: node:20.15.0-slim@sha256:1d05ae8a4d16d201ba911ba7bde30d25d079eb7e27feaf7a99fc383b2ff63fc0
  environment:
    NODE_ENV: development
  # cpu_count: 1
  # mem_limit: "268435456"
  ports:
    - "9229:9229"
  restart: unless-stopped
  # env_file: .env
  tty: true
  working_dir: /app


services:
  ui:
    <<: *node-app-dev
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    command: npm run start



